### ISSUE TITLE
Feature request: alterar disciplinas obrigatórias

### ISSUE THREAD

**Issue by lucasoshiro** [akaFTS/yggdrasil2#4]
Oi,
As disciplinas obrigatórias mostradas não podem ser alteradas. A minha lista de disciplinas obrigatórias, porém, é diferente devido às alterações do currículo do BCC, e isso gera diferenças entre o relatório obtido e o meu resumo escolar... Seria possível incluir nele alguma forma de alterar isso?

**Comment by akaFTS** [comment]
Por ser um caso bastante específico da época da migração do currículo, não vale a pena fazer modificações tão profundas. Recomendo deixar explicado nas observações do relatório qualquer divergência entre as disciplinas.
