### ISSUE TITLE
Confusão na sessão de e-science

### ISSUE THREAD

**Issue by mrfelipenoronha** [akaFTS/yggdrasil2#6]
Na sessão de e-science é dito "o aluno deverá completar os três núcleos". Porém, existem 4 núcleos disponíveis para escolha. Uma alternativa seria substituir por "o aluno devera completar três dos quatro núcleos disponíveis".

**Comment by akaFTS** [comment]
Os quatro núcleos são necessários, mas no momento que esse textinho foi escrito só haviam três.

Já consertei. Sorry!
